# Generated by Django 4.2.3 on 2023-08-11 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noutbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noutbooksmodel',
            name='ram',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noutbook.noutbooksmodel')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
